name: Auto Markdown to Word-docx

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install pandoc
      run: |
        sudo apt-get install pandoc
        sudo apt-get install npm
        npm install --global mermaid-filter
      
    - name: Run pandoc
      run: |
        cd mds
        find ./ -type d -exec mkdir -p ../docs/\{\} \;
        find ./ -iname "*.md" -type f -exec sh -c 'pandoc "${0}" -o "../docs/$(dirname ${0})/$(basename ${0%.md}.docx)" -F mermaid-filter' {} \;

    - name: commit
      run: |
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        git add .
        git commit -m "Auto commit from [Auto Markdown to Word-docx]" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
