name: Auto Markdown to Word-docx

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install pandoc
      run: apt-get install pandoc
      
    - name: Run pandoc
      run: |
        cd mds
        find ./ -type d -exec mkdir -p ../docs/\{\} \;
        find ./ -iname "*.md" -type f -exec sh -c 'pandoc "${0}" -o "../docs/$(dirname ${0})/$(basename ${0%.md}.docx)"' {} \;


