name: Auto Markdown to Word-docx

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Install pandoc
      run: sudo apt-get install pandoc
      
    - name: Run pandoc
      run: |
        cd mds
        find ./ -type d -exec mkdir -p ../docs/\{\} \;
        find ./ -iname "*.md" -type f -exec sh -c 'pandoc "${0}" -o "../docs/$(dirname ${0})/$(basename ${0%.md}.docx)"' {} \;

    - name: commit
      run: |
        git config --global user.email 724180662@163.com
        git config --global user.name LoyieKing
        git add .
        git commit -m "Auto commit from [Auto Markdown to Word-docx]" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
